[tool.poetry]
name = "aiorussound"
version = "3.0.1"
description = "Asyncio client for Russound RIO devices."
authors = ["Noah Husby <opensource@husbylabs.com>"]
maintainers = ["Noah Husby <opensource@husbylabs.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/noahhusby/aiorussound"
repository = "https://github.com/noahhusby/aiorussound"
documentation = "https://github.com/noahhusby/aiorussound"


[tool.poetry.dependencies]
python = "^3.11"
mashumaro = "^3.11"
orjson = ">=3.9.0"

[tool.poetry.group.dev.dependencies]
coverage = {version = "7.6.1"}
mypy = "1.11.2"
pre-commit = "3.8.0"
pre-commit-hooks = "4.6.0"
pylint = "3.2.7"
pytest = "8.3.2"
pytest-asyncio = "0.24.0"
pytest-cov = "5.0.0"
ruff = "0.6.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
