[tool.poetry]
name = "aiorussound"
version = "4.3.0"
description = "Asyncio client for Russound RIO devices."
authors = ["Noah Husby <opensource@husbylabs.com>"]
maintainers = ["Noah Husby <opensource@husbylabs.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/noahhusby/aiorussound"
repository = "https://github.com/noahhusby/aiorussound"
documentation = "https://github.com/noahhusby/aiorussound"


[tool.poetry.dependencies]
python = "^3.11"
mashumaro = "^3.11"
orjson = ">=3.9.0"

[tool.poetry.group.dev.dependencies]
coverage = {version = "7.6.9"}
mypy = "1.14.0"
pre-commit = "4.0.1"
pre-commit-hooks = "5.0.0"
pylint = "3.3.2"
pytest = "8.3.4"
pytest-asyncio = "0.25.0"
pytest-cov = "6.0.0"
ruff = "0.8.4"

[tool.poetry.group.docs.dependencies]
pdoc = ">=14.7,<16.0"


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
